name: release

on:
  push:
    paths:
      - ".changeset/**"
      - ".github/**"
      - "packages/**"
      - "package.json"
      - "package-lock.json"
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Download Turborepo cache
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: node_modules/.cache/turbo
          key: ${{ runner.os }}-node-20-turbo-${{ hashFiles('node_modules/.cache/turbo') }}
          restore-keys: |
            ${{ runner.os }}-node-20-turbo-

      - name: Check types
        run: npm run tsc

      - name: Build packages
        run: npm run build

      - name: Run tests
        run: npm run test -- --ci --maxWorkers=2

      - name: Create Release Pull Request or Publish Packages
        id: changesets
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b # v1.8.0
        with:
          version: npm run changeset:version
          publish: npm run changeset:publish
          commit: "chore(release): version packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
